#!/usr/bin/env bash
# 
# Watch and print X and Y screen tap coordinates of an Android device.
# 
# Output is converted from hexidecimal to decimal for easy readability.
# 
# Usage:
#   getmobiletappos [seconds]
# 
#   seconds (optional): number of seconds to watch for tap events.
# 

# ======= CONFIGURATIONS ==============

# Defult number of seconds to watch for tap events.
readonly WATCH_TIME=5

# ======= ! CONFIGURATIONS ==============

if [ "$#" -ge 2 ]; then
  watchTime="${2}"
else
  watchTime="${WATCH_TIME}"
fi

hxecho() {
  echo -n "$((16#"${1}"))"
}

export -f hxecho

timeout "${watchTime}" adb -d shell getevent -l /dev/input/event2 | sed \
    's/\(.*ABS_MT_POSITION..[^0]*\)\(.*\)/echo -n "\1 "; hxecho \2/e'

