#!/usr/bin/env bash
# 
# Replace a string recursively.
# 
# Regex characters in both the original and replacement texts are escaped,
# allowing string matches and replacements to be made exactly as they are typed.
# An option is provided to backup the directory in which replacements are made
# recursively.
# 
# Usage:
#   replrec <text to replace> <replacement text>
# 

# ======= CONFIGURATIONS ==============

# Backup the directory in which text is being replaced recursively.
readonly BACKUP=true

# Directory where backups are stored
readonly BACKUPS_DIR="${HOME}/.unixfoundation/shell/replrec-backups/"

# ======= ! CONFIGURATIONS ==============

if [ "$#" -ne 2 ]; then
  echo 'replrec: invalid number of arguments' 1>&2
  exit 1
elif [ -z "${1}" ]; then
  echo 'replrec: first argument empty' 1>&2
  exit 1
fi

if [ "${BACKUP}" != 'false' ]; then
  if [ ! -d "${BACKUPS_DIR}" ]; then
    mkdir -p "${BACKUPS_DIR}"
  fi

  cp -R "$PWD" "${BACKUPS_DIR}"
fi

ARGS[0]="$(echo "${1}" | sed 's/[]\/$*.^|[]/\\&/g')"
ARGS[1]="$(echo "${2}" | sed 's/[\/&]/\\&/g')"

find . -type f -print0 | xargs -0 sed -i "s/${ARGS[0]}/${ARGS[1]}/g"

