#!/usr/bin/env bash
# 
# File:
#   turnmobilescreenoff
# 
# Description:
#   Turn an Android device screen off if on.
# 

readonly IS_SCREEN_ON="$(adb -d shell 'dumpsys power' | grep mScreenOn)"

if [[ "${IS_SCREEN_ON##*=}" = *'true'* ]]; then
  adb -d shell 'input keyevent KEYCODE_POWER;'
fi

