#!/usr/bin/env bash
# 
# File:
#   getactvwindname
# 
# Description:
#   Get the name of the active window.
# 

getActvWindId() {
  echo "$(xprop -root _NET_ACTIVE_WINDOW | cut -d ' ' -f 5 | rev | cut -c 2- | \
      rev | sed 's/^0x/0x0/')"
}

WINDOW_NAME="$(xprop -id "$(getActvWindId)" WM_NAME | sed -e \
    's/.*"\(.*\)".*/\1/')"

echo "${WINDOW_NAME}"



# Alternative method:
# 
# WINDOW_NAME=$(wmctrl -l | grep "$(getActvWindId)" | awk \
#     '{$1=$2=$3=""; print $0}' | sed 's/^[ \t]*//')

