#!/usr/bin/env bash
# 
# File:
#   getwindidbyname
# 
# Description:
#   Get the ID of a window by name.
# 
# Usage:
#   getwindidbyname <window_name>
# 
#   <window_name>: case-sensitive; matched partially
# 
# Returns:
#   window ID; multiple IDs if more than one window is matched
# 

if [ "$#" -eq 0 ]; then
  exit 1
fi

WINDOW_IDS=("$(wmctrl -l | awk -v srchTxt="${1}" '{$2=$3=""; wn = \
    gensub(/([^ ]*[ ]+)(.*)/, "\\2", "g", $0)} wn ~ srchTxt {print $1}')")

if [ "${#WINDOW_IDS[@]}" -gt 0 ] && [ -n "${WINDOW_IDS[0]}" ]; then
  echo "${WINDOW_IDS[@]}"
fi

