#!/usr/bin/env bash
# 
# File:
#   getmobilescreentappos
# 
# Description:
#   Watch for and print X and Y tap coordinates on an Android device screen.
# 
# Supplemental feature:
#   Output is converted from hexidecimal to decimal for easy readability.
# 
# Usage:
#   getmobilescreentappos [seconds]
# 
#   [seconds]: (optional) number of seconds to watch for tap events
# 

# ======= CONFIGURATIONS ==============

# Defult number of seconds to watch for tap events
readonly DEFAULT_WATCH_TIME=25

# ======= ! CONFIGURATIONS ==============

if [ "$#" -ge 2 ]; then
  watchTime="${2}"
else
  watchTime="${DEFAULT_WATCH_TIME}"
fi

hxecho() {
  echo -n "$((16#"${1}"))"
}

export -f hxecho

timeout "${watchTime}" adb -d shell getevent -l /dev/input/event2 | sed \
    's/\(.*ABS_MT_POSITION..[^0]*\)\(.*\)/echo -n "\1 "; hxecho \2/e'

