#!/usr/bin/env bash
# 
# File:
#   turnandroiddevscreenoff
# 
# Description:
#   Turn an Android device screen off.
# 

readonly IS_SCREEN_ON="$(adb -d shell 'dumpsys power' | grep \
      'mHoldingDisplaySuspendBlocker=')"

if [[ "${IS_SCREEN_ON##*=}" = *'true'* ]]; then
  adb -d shell 'input keyevent KEYCODE_POWER;'
fi

