#!/usr/bin/env bash
# 
# File:
#   issecondarywlanblocked
# 
# Description:
#   Check if a secondary wireless local area network device interface is soft
#   blocked.
# 
# Exit codes:
#   0: is blocked
#   1: is not blocked
# 
# Note:
#   The primary WLAN device interface will be checked if a secondary one does
#   not exist.
# 

IS_BLOCKED="$(rfkill list wlan | sed -n 's/Soft blocked: \(.*\)/\1/p' | \
    tail -1 | sed 's/^[ \t]*//;s/[ \t]*$//')"

if [ "${IS_BLOCKED}" = 'yes' ]; then
  exit 0
else
  exit 1
fi

