#!/usr/bin/env bash
# 
# File:
#   recrep
# 
# Description:
#   Recursively replace a string in all files.
# 
# Additional feature:
#   This script allows a backup directory to be created of the directories in
#   which it is run.
# 
# Usage:
#   recrep <text_to_replace> <replacement_text>
# 
# Notes:
#   All characters in both arguments are accepted as literals.
# 

# ======= CONFIGURATIONS ==============

# Backup the directory in which this script is run
readonly BACKUP=true

# Directory where backup directories are created
readonly BACKUPS_DIR="${HOME}/.unixfoundation/shell/recrep-backups/"

# ======= ! CONFIGURATIONS ==============

if [ "$#" -ne 2 ]; then
  echo 'recrep: invalid number of arguments' 1>&2
  exit 1
elif [ -z "${1}" ]; then
  echo 'recrep: first argument empty' 1>&2
  exit 1
fi

if [ "${BACKUP}" != 'false' ]; then
  if [ ! -d "${BACKUPS_DIR}" ]; then
    mkdir -p "${BACKUPS_DIR}"
  fi

  cp -R "$PWD" "${BACKUPS_DIR}"
fi

ARGS[0]="$(echo "${1}" | sed 's/[]\/$*.^|[]/\\&/g')"
ARGS[1]="$(echo "${2}" | sed 's/[\/&]/\\&/g')"

find . -type f -print0 | xargs -0 sed -i "s/${ARGS[0]}/${ARGS[1]}/g"

