#!/usr/bin/env bash
# 
# File:
#   inotify
# 
# Description:
#   Run a command when files have changed in the current directory. 
# 
# Usage:
#   inotify <command to run>
# 
# Usage note:
#   Run this script in the directory it is to monitor.
# 
# Dependencies:
#   inotify-tools
# 

readonly FORMAT="$(echo -e "\033[1;33m%w%f\033[0m written")"

while inotifywait -qre close_write --format "${FORMAT}" .; do
  # This section will run once when files have changed in the directory.
  "${@}"
done

