#!/usr/bin/env bash
# 
# File:
#   getfirstwindnameinclass
# 
# Description:
#   Get the name of the first active window in a class.
# 
# Usage:
#   getfirstwindnameinclass <window_class>
# 
#   <window_class>: case-sensitive; can match any part of the full qualified
#                   class string (i.e. class and classname; e.g. "xterm.XTerm")
# 

if [ "$#" -eq 0 ]; then
  exit 1
fi

getWindNamesInClass() {
  echo "$(wmctrl -lx | awk '{printf "%s", $3; $1=$2=$3=$4=""; print $0}' | awk \
      -v class="${1}" '$1 ~ class {$1=""; sub(/^[ \t]+/, "", $0); print $0}')"
}

IFS=$'\n'
CLASS_WIND_NAMES=($(getWindNamesInClass "${1}"))
unset IFS

if [ ${#CLASS_WIND_NAMES[@]} -eq 0 ]; then
  exit
fi

echo "${CLASS_WIND_NAMES[0]}"

