#!/usr/bin/env bash
# 
# File:
#   getwindidsinclass
# 
# Description:
#   Get the IDs of all windows in a class.
# 
# Usage:
#   getwindidsinclass <window_class>
# 
#   <window_class>: case-sensitive; can match any part of the full qualified
#                   class string (class and classname; e.g. "xterm.XTerm")
# 
# Returns:
#   Window IDs in hexidecimal format separated by a space
# 

if [ "$#" -eq 0 ]; then
  exit 1
fi

WINDOW_IDS=($(wmctrl -lx | awk -v class="${1}" '$3 ~ class {print $1}'))

if [ "${#WINDOW_IDS[@]}" -gt 0 ]; then
  echo "${WINDOW_IDS[@]}"
fi

