#!/usr/bin/env bash
# 
# File:
#   getwindnamesinclass
# 
# Description:
#   Get the names of all windows in a class.
# 
# Usage:
#   getwindnamesinclass <window_class>
# 
#   <window_class>: case-sensitive; can match any part of the full qualified
#                   class string (i.e. class and classname; e.g. "xterm.XTerm")
# 

if [ "$#" -eq 0 ]; then
  exit 1
fi

WIND_NAMES=("$(wmctrl -lx | awk \
    '{printf "%s", $3; $1=$2=$3=$4=""; print $0}' | awk -v class="${1}" \
    '$1 ~ class {$1=""; sub(/^[ \t]+/, "", $0); print $0}')")

if [ "${#WIND_NAMES[@]}" -gt 0 ] && [ -n "${WIND_NAMES[0]}" ]; then
  echo "${WIND_NAMES[@]}"
fi

