#!/usr/bin/env bash
# 
# Get the class of a window by name.
# 
# Usage:
#   getwindclassbyname <window name>
# 
#   window name: case-sensitive; matched partially
# 
# Returns:
#   Full qualified class string (i.e. class and classname; e.g. "xterm.XTerm");
#   if more than one class is found for all matched windows, each class will be
#   returned separated by a newline.
# 

if [ "$#" -eq 0 ]; then
  exit 1
fi

WINDOW_CLASSES=("$(wmctrl -lx | awk -v srchTxt="${1}" '{$1=$2=$4=""; wn = \
    gensub(/([^ ]+[ ]+)(.*)/, "\\2", "g", $0); gsub(/ /, "", wn)} wn ~ srchTxt \
    {print $3}' | sort | uniq)")

if [[ "${#WINDOW_CLASSES[@]}" -gt 0 && -n "${WINDOW_CLASSES[0]}" ]]; then
  echo "${WINDOW_CLASSES[@]}"
fi

