#!/usr/bin/env bash
# 
# File:
#   mongodbutils
# 
# Description:
#   MongoDB general NoSQL utility functions
# 
# Usage:
#   mongodbutils <action>
# 

if [ "$#" -lt 1 ]; then
  echo -e 'mongodbutils: invalid number of arguments; action required' 1>&2
  exit 1
fi

case "${1}" in
  # Action:
  #   drop_all
  # Description:
  #   Drop all databases.
  # Usage:
  #   ... drop_all
  'drop_all')
    /usr/bin/mongo <<-EOF
			db.getMongo().getDBNames().forEach(function(database) {
				if (database != 'local' && database != 'admin') {
					db = db.getMongo().getDB(database);
					db.dropDatabase();
					print('dropped database ' + db.getName());
				}
			})
		EOF
    ;;

  *)
    echo "mongodbutils: unknown action \"${1}\"" 1>&2
    exit 1
    ;;

esac

