#!/usr/bin/env bash
# 
# Get the ID of a window by name.
# 
# Usage:
#   getwindidbyname <window name>
# 
#   window name: case-sensitive; matched partially
# 
# Returns:
#   ID of window; if more than one window is matched, all IDs are returned.
# 

if [ "$#" -eq 0 ]; then
  exit 1
fi

WINDOW_IDS=("$(wmctrl -l | awk -v srchTxt="${1}" '{$2=$3=""; wn = \
    gensub(/([^ ]*[ ]+)(.*)/, "\\2", "g", $0)} wn ~ srchTxt {print $1}')")

if [[ "${#WINDOW_IDS[@]}" -gt 0 && -n "${WINDOW_IDS[0]}" ]]; then
  echo "${WINDOW_IDS[@]}"
fi



# Alternative method:
# 
# WINDOW_IDS=($(xdotool search --name "${1}"))
# for i in ${!WINDOW_IDS[@]}; do
#   WINDOW_IDS[${i}]="$(printf '%#010x\n' "${WINDOW_IDS[${i}]}")"
# done

