#!/usr/bin/env bash
# 
# File:
#   sendtextmesgviaandroiddev
# 
# Description:
#   Send a test message via an Android device.
# 
# Usage:
#   sendtextmesgviaandroiddev <phone_number> <message>
# 
#       <message>: may contain "\n" for newlines
# 
# Notes:
#   If the message fails to send and simply opens up the thread of the contact
#   of whom the message is being sent to, click the back button from the thread.
# 

if [ "$#" -lt 2 ]; then
  echo 'sendtextmesgviaandroiddev: invalid number of arguments' 1>&2
  exit 1
fi

readonly PHONE_NUMBER="${1}"
shift
readonly MESSAGE="$(echo "${@}" | sed 's/\\n/${NL}/g')"

# Screen must be on for an sms to be sent using this method.
isScreenOn="$(adb -d shell 'dumpsys power' | grep mScreenOn)"

# Exit if no device was found.
if [ $? -eq 1 ]; then
  exit
fi

if [[ "${isScreenOn##*=}" = *'false'* ]]; then
  adb -d shell 'input keyevent KEYCODE_POWER;'
fi

adb -d shell "NL=$'\n' ; am start -a android.intent.action.SENDTO -d \
    sms:${PHONE_NUMBER} --es sms_body \"${MESSAGE}\" --ez exit_on_sent true; \
    input keyevent 66" >/dev/null

