#!/usr/bin/env bash
# 
# Generic RDBMS functions for MySQL
# 
# Usage:
#   mysqlutil <databaes user> <database name> <action>
# 

if [ "$#" -lt 3 ]; then
  echo -e  'mysqlutil: invalid number of arguments; database user,\n' \
      '  database name and action required' 1>&2
  exit 1
fi

DB_USER="${1}"
DB_NAME="${2}"
ACTION="${3}"
shift 3

case "${ACTION}" in
  # Create the database from an SQL file.
  # Usage:
  #   ... create <create SQL file>
  'create')
    if [ "$#" -eq 0 ]; then
      echo "mysqlutil: no SQL file specified" 1>&2
      exit 1
    fi
    if [ ! -f "${1}" ]; then
      echo "mysqlutil: file \"${1}\" not found" 1>&2
      exit 1
    fi

    mysql -u"${DB_USER}" -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME}"

    if mysql -u"${DB_USER}" -e "use ${DB_NAME}" 2>/dev/null; then
      bash ${0} 'droptables' "${DB_USER}" "${DB_NAME}"
      mysql -u"${DB_USER}" "${DB_NAME}" < "${1}"
    else
      echo "mysqlutil: database \"${DB_NAME}\" not found" 1>&2
    fi
    ;;
    
  # Drop all tables in the database.
  # Usage:
  #   ... droptables
  'droptables')
    Q1="
      USE ${DB_NAME};
      SET FOREIGN_KEY_CHECKS = 0;
      SET GROUP_CONCAT_MAX_LEN=32768;
      SET @tables = NULL;
      SELECT GROUP_CONCAT('\`', table_name, '\`') INTO @tables
        FROM information_schema.tables
        WHERE table_schema = (SELECT DATABASE());
      SELECT IFNULL(@tables,'dummy') INTO @tables;

      SET @tables = CONCAT('DROP TABLE IF EXISTS ', @tables);
      PREPARE stmt FROM @tables;
      EXECUTE stmt;
      DEALLOCATE PREPARE stmt;
      SET FOREIGN_KEY_CHECKS = 1;
      "
    mysql -u"${DB_USER}" -e "${Q1}"
    ;;
    
  # Clear data from all tables in the database.
  # Usage:
  #   ... cleardata
  'cleardata')
    mysqldump -d -u"${DB_USER}" --add-drop-table "${DB_NAME}" > \
        ./db_export_tmp.sql
    mysql -u"${DB_USER}" "${DB_NAME}" < ./db_export_tmp.sql
    rm ./db_export_tmp.sql
    ;;
    
  # Export the database.
  # Usage:
  #   ... export
  'export')
    mysqldump -u"${DB_USER}" "${DB_NAME}" > ./db_"${DB_NAME}"_export.sql
    ;;
    
  *)
    echo "mysqlutil: unknown action \"${ACTION}\"" 1>&2
    ;;

esac

