#!/usr/bin/env bash
# 
# Run a countdown timer in the terminal.
# 
# Usage:
#   runcountdowntimer <seconds>
# 
# Source:
#   https://superuser.com/a/611582
# 

# ======= CONFIGURATIONS ==============

# Set this to true to print days also.
readonly PRINT_DAYS_ALSO=false

# ======= ! CONFIGURATIONS ==============

if [ "$#" -eq 0 ]; then
  echo 'runcountdowntimer: time required in seconds' 1>&2
  exit 1
elif [[ ! "${1}" =~ ^[0-9]+$ ]]; then
  echo 'runcountdowntimer: argument must be a number (seconds)' 1>&2
  exit 1
fi

currDate="$(date +%s)"
readonly DATE_START="$((currDate + "${1}"))"

while [ "${DATE_START}" -ge "${currDate}" ]; do
  sleep 0.1

  currDate="$(date +%s)"
  secondsRemaining="$((DATE_START - currDate))"
  secondsFrmtd="$(date -u --date @${secondsRemaining} +%H:%M:%S)"

  if [ "${PRINT_DAYS_ALSO}" = 'true' ]; then
    days="$(( ( DATE_START - currDate * 1 ) / 86400 ))"
    output="     ${days} day(s) and ${secondsFrmtd}\r"
  else
    output="     ${secondsFrmtd}\r"
  fi

  echo -ne "${output}"
done

