#!/usr/bin/env bash
# 
# File:
#   renmrecr
# 
# Description:
#   Rename all files matching a name recursively.
# 
# Usage:
#   renmrecr <old_file_name> <new_file_name>
# 

if [ "$#" -ne 2 ]; then
  echo 'renmrecr: invalid number of arguments' 1>&2
  exit 1
fi

find . -depth -type f -name "${1}" | while IFS= read -r file; do
  mv -i "${file}" "$(dirname "${file}")/${2}"
done

