#!/usr/bin/env bash
# 
# File:
#   mountmtpdev
# 
# Description:
#   Mount and unmount an MTP device.
# 
# Usage:
#   mountmtpdev <action>
# 
#   <action>:
#     "mount" or "m" to mount
#     "umount" or "u" to unmount
# 
# Dependencies:
#   jmtpfs
# 
# Set up:
#   Create user group "fuse" and add the current system user to it by running
#   the following commands:
#       sudo groupadd fuse
#       sudo gpasswd -a "${USER}" fuse
# 
# Note:
#   This has only been tested with Android devices.
# 

# ======= CONFIGURATIONS ==============

# Mountpoint path of MTP device
MNTPNT_PATH='/mnt/mtp'

# ======= ! CONFIGURATIONS ==============

if [ "$#" -eq 0 ]; then
  echo 'mountmtpdev: no arguments: "mount", "unmount", "m" or "u" required' \
      1>&2
  exit 1
fi

case "${1}" in
  'mount' | 'm')
    if [ ! -d "${MNTPNT_PATH}" ]; then
      mkdir "${MNTPNT_PATH}"
    fi

    if ! mount | grep "${MNTPNT_PATH}" >/dev/null; then
      jmtpfs "${MNTPNT_PATH}"

      if mount | grep "${MNTPNT_PATH}" >/dev/null; then
        # newline prepended to separate message from jmtpfs output
        echo -e "\nmountmtpdev: successfully mounted device on ${MNTPNT_PATH}"
      fi
    fi
    ;;
    
  'unmount' | 'u')
    if ! mountpoint "${MNTPNT_PATH}" >/dev/null; then
      echo "mountmtpdev: device not mounted on ${MNTPNT_PATH}" 1>&2
      exit 1
    fi
    if [[ "$PWD" = "${MNTPNT_PATH}"* ]]; then
      echo "mountmtpdev: must leave mountpoint directory" 1>&2
      exit 1
    fi

    fusermount -u "${MNTPNT_PATH}"

    if [ "$?" -eq 0 ] && ! mount | grep "${MNTPNT_PATH}" >/dev/null; then
      echo "mountmtpdev: successfully unmounted device from ${MNTPNT_PATH}"
    fi
    ;;
    
  *)
    echo 'mountmtpdev: action unknown: "mount", "unmount", "m" or "u"'\
        'required' 1>&2
    exit 1
    ;;
esac

