#!/usr/bin/env bash
# 
# File:
#   execonfilechange
# 
# Description:
#   Execute a command when a file has changed in the current directory.
# 
# Usage:
#   execonfilechange <command>
# 
# Usage note:
#   Run this script in the directory it is to monitor.
# 
# Dependencies:
#   inotify-tools
# 

readonly FORMAT="$(echo -e "\033[1;33m%w%f\033[0m written")"

while inotifywait -qre close_write --format "${FORMAT}" .; do
  # This section will run once a file has changed in the current directory.
  ${@}
  echo '[+] execonfilechange: command executed'
done

