#!/usr/bin/env bash
# 
# File:
#   runstopwatch
# 
# Description:
#   Run a stopwatch in the terminal.
# 
# Usage:
#   runstopwatch
# 
# Source:
#   https://superuser.com/a/611582
# 

# ======= CONFIGURATIONS ==============

# Set this to true to print days also.
readonly PRINT_DAYS_ALSO=false

# ======= ! CONFIGURATIONS ==============

readonly DATE_START="$(date +%s)"

while true; do
  dateNow="$(date +%s)"
  secondsElapsed="$((dateNow - DATE_START))"
  secondsFrmtd="$(date -u --date @${secondsElapsed} +%H:%M:%S)"

  if [ "${PRINT_DAYS_ALSO}" = 'true' ]; then
    days=$(( ( dateNow - DATE_START ) / 86400 ))
    output="     ${days} day(s) and ${secondsFrmtd}\r"
  else
    output="     ${secondsFrmtd}\r"
  fi

  echo -ne "${output}"

  sleep 0.1
done

