#!/usr/bin/env bash
# 
# Turn an Android device screen on if off.
# 

readonly IS_SCREEN_ON="$(adb -d shell 'dumpsys power' | grep mScreenOn)"

if [[ "${IS_SCREEN_ON##*=}" = *'false'* ]]; then
  adb -d shell 'input keyevent KEYCODE_POWER;'
fi

