#!/usr/bin/env bash
# 
# File:
#   remlastnbashhistentries
# 
# Description:
#   Remove the last N bash history entries.
# 
# Usage (script must be sourced for history command to work):
#   source remlastnbashhistentries; _remlastnbashhistentries <1-100>
# 
# Source:
#   http://unix.stackexchange.com/a/65076
# 

_remlastnbashhistentries() {
  local numCurrHistEntries="$(history | wc -l)"

  if [ "$#" -eq 0 ]; then
    echo -e 'remlastnbashhistentries: no argument' 1>&2
    return 1
  elif [[ ! "${1}" =~ ^[0-9]+$ || "${1}" -lt 1 || "${1}" -gt 100 ]]; then
    echo -e 'remlastnbashhistentries: invalid argument; must be a number\n'\
        ' between 1 and 100 (inclusive)' 1>&2
    return 1
  fi

  local count="${1}"
  local start=$((numCurrHistEntries - count))

  while [ "${count}" -ge 0 ]; do
    history -d "${start}"
    ((count--))
  done
}

