#!/usr/bin/env bash
# 
# File:
#   issecondarywlanblocked
# 
# Description:
#   Check if a secondary wireless local area network device (such as a USB Wi-Fi
#   adapter) is soft blocked.
# 
# Note:
#   The primary WLAN device will be checked if a secondary one does not exist.
# 

IS_SECONDARY_WLAN_SOFT_BLOCKED="$(rfkill list wlan | sed -n \
    's/Soft blocked: \(.*\)/\1/p' | tail -1 | sed 's/^[ \t]*//;s/[ \t]*$//')"

if [ "${IS_SECONDARY_WLAN_SOFT_BLOCKED}" = 'yes' ]; then
  exit 0
else
  exit 1
fi

